#!/usr/bin/env bash
# run-g4.sh — compile, bring the G4 localnet up, run the bridge end-to-end driver, tear down.
#
# Project 00034, sub-plan plans/00034-sub-g-account-bridge.md, phase G4.
#
# Usage:
#   ./run-g4.sh compile     # the vault, the singleton and the account (offline, no Docker)
#   ./run-g4.sh up          # node, indexer, proof server, anvil (NOT fakenet — see below)
#   ./run-g4.sh e2e         # the driver; it starts fakenet itself once the singleton exists
#   ./run-g4.sh down        # docker compose down -v
#   ./run-g4.sh logs        # fakenet responder logs
#   ./run-g4.sh all         # compile + up + e2e + down
#
# HOST RULE: only ONE localnet stack runs on this host at a time. Before `up`, read the
# "Stack in use" line at the top of
# plans/00034-passport-evm-account-zswap-questions.md; claim it there, and clear it after
# `down`. This script does not touch that file — claiming is an agent decision, not a side
# effect of running a command.
#
# The compose file is PR-F's (contracts/erc20-vault/infra/docker-compose.yml): the stack is
# the same five containers, and one definition is better than two that drift. Only the
# project name and the ports differ, so a G4 run and an F4 run can never collide.
#
# fakenet is deliberately NOT started by `up`: it needs MPC_ROOT_KEY and the singleton's
# address, and both exist only after the driver has generated the key and deployed the
# contract. The driver starts it itself at step S2.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_DIR="$SCRIPT_DIR/contracts/erc20-vault"
INFRA_DIR="$VAULT_DIR/infra"

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-prg-bridge}"
export NODE_PORT="${NODE_PORT:-21744}"
export NODE_P2P_PORT="${NODE_P2P_PORT:-21733}"
export INDEXER_PORT="${INDEXER_PORT:-21188}"
export PROOF_PORT="${PROOF_PORT:-21400}"
export EVM_PORT="${EVM_PORT:-21545}"

export NODE_URL="http://localhost:$NODE_PORT"
export MIDNIGHT_NODE_URL="$NODE_URL"
export INDEXER_URL="http://localhost:$INDEXER_PORT/api/v4/graphql"
export INDEXER_WS_URL="ws://localhost:$INDEXER_PORT/api/v4/graphql/ws"
export PROOF_SERVER_URL="http://127.0.0.1:$PROOF_PORT"
export MIDNIGHT_PROOF_SERVER_URL="$PROOF_SERVER_URL"
export EVM_RPC_URL="http://127.0.0.1:$EVM_PORT"
export MIDNIGHT_NETWORK=local
export MIDNIGHT_NETWORK_ID=undeployed

compose() { docker compose -f "$INFRA_DIR/docker-compose.yml" --env-file "$INFRA_DIR/.env" "$@"; }

ensure_env() {
  if [[ ! -f "$INFRA_DIR/.env" ]]; then
    cat > "$INFRA_DIR/.env" <<EOF
# Generated by run-g4.sh — never committed (see .gitignore).
APP__INFRA__SECRET=$(openssl rand -hex 32)

# Fixed demo seed (do not use in production). The dev node genesis funds it.
WALLET_SEED=0000000000000000000000000000000000000000000000000000000000000001
EOF
    echo "infra/.env created"
  fi
  set -a; source "$INFRA_DIR/.env"; set +a
}

do_compile() {
  cd "$VAULT_DIR"
  echo "=== the vault and the singleton (callees first — the artefact directory name IS the ABI)"
  npm run compile
  cd "$SCRIPT_DIR"
  echo "=== the account (links contracts/managed/{Erc20Vault,SignetSigner}, then compiles)"
  npm run compile:account
}

wait_for() {
  local label="$1" url="$2" limit="$3"; shift 3
  printf "Waiting for %s" "$label"
  local elapsed=0
  until curl -sf "$url" "$@" > /dev/null 2>&1; do
    if (( elapsed >= limit )); then echo " NOT READY"; return 1; fi
    printf "."; sleep 2; (( elapsed += 2 ))
  done
  echo " OK"
}

do_up() {
  ensure_env
  cd "$VAULT_DIR"
  echo "=== G4 localnet: project $COMPOSE_PROJECT_NAME, ports $NODE_PORT/$INDEXER_PORT/$PROOF_PORT/$EVM_PORT ==="
  compose up -d node indexer proof-server evm
  wait_for "node" "http://localhost:$NODE_PORT/health" 90 || { compose logs node --tail 30; exit 1; }
  # Cold-start quirk: an indexer started before the node produces block 1 can exit once.
  printf "Waiting for indexer"
  local elapsed=0
  until curl -sf "http://localhost:$INDEXER_PORT/api/v4/graphql" -H 'Content-Type: application/json' \
      -d '{"query":"{ __typename }"}' > /dev/null 2>&1; do
    if (( elapsed >= 180 )); then echo " NOT READY"; compose logs indexer --tail 30; break; fi
    if (( elapsed > 0 && elapsed % 21 == 0 )); then compose up -d indexer > /dev/null 2>&1 || true; fi
    printf "."; sleep 3; (( elapsed += 3 ))
  done
  echo " OK"
  wait_for "proof server" "http://localhost:$PROOF_PORT/version" 60 || true
  wait_for "anvil" "$EVM_RPC_URL" 60 -H 'Content-Type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' || { compose logs evm --tail 20; exit 1; }
}

do_e2e() {
  ensure_env
  cd "$SCRIPT_DIR"
  npm run test:bridge-e2e
}

do_logs() { ensure_env; cd "$VAULT_DIR"; compose logs fakenet --tail "${1:-80}"; }

do_down() {
  ensure_env
  cd "$VAULT_DIR"
  compose --profile fakenet down -v || true
  rm -rf "$SCRIPT_DIR/midnight-level-db" "$VAULT_DIR/midnight-level-db"
  echo "stack down, volumes removed"
}

CMD="${1:-all}"; shift || true
case "$CMD" in
  compile) do_compile ;;
  up)      do_up ;;
  e2e)     do_e2e ;;
  logs)    do_logs "$@" ;;
  down)    do_down ;;
  all)     do_compile; do_up; do_e2e; do_down ;;
  *)       echo "usage: $0 {compile|up|e2e|logs|down|all}"; exit 2 ;;
esac
