// Generator for `passport-evm-v1.json` — the frozen vector set of
// AUTH-EIP712-PASSPORT-EVM-V1.
//
// Run: npm run fixtures:evm        (writes the file)
//      npm run fixtures:evm -- --check   (regenerates and diffs; non-zero exit
//                                         if a single byte moved)
//
// Determinism is the point: the file is regenerated byte-identically on every
// run, so a diff means the byte contract moved and needs a new version. The
// randomness is an xorshift64* over a fixed seed, never the system RNG.
//
// The generator depends on `src/wallet/eip712.ts` and `src/wallet/evm-signature.ts`
// only — no Compact runtime, no node, no wallet. `src/tests/eip712-evm-offline.ts`
// then reproduces every digest in this file with ethers alone, which is the
// second, independent implementation spec SC-006 asks for.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  DOMAIN_ENCODE_TYPE,
  DOMAIN_NAME,
  DOMAIN_NAME_HASH,
  DOMAIN_TYPE_HASH,
  DOMAIN_VERSION,
  DOMAIN_VERSION_HASH,
  EVM_OPS,
  TYPE_DEFINITIONS,
  TYPE_HASHES,
  buildTypedData,
  computeDigest,
  encodeStruct,
  fromHex,
  toHex,
  type EvmMessage,
  type EvmOp,
} from '../../wallet/eip712.js';
import {
  SECP256K1_N,
  addressForPrivateKey,
  highSTwin,
  parseSignature,
  publicPointForPrivateKey,
  recoverPoint,
  serializeSignature,
  signDigest,
  verifyDigest,
} from '../../wallet/evm-signature.js';

/** FIXTURES-3 adds the bridge types of project 00034 PR-G to this file. The byte contract
 *  itself is unchanged — no existing type string, type hash or KAT digest moved — so the
 *  document stays `…-V1`; what changed is the SET of vectors, and the random ones shifted
 *  because the round robin now runs over nine operations instead of seven.
 *
 *  The number skips 2 on purpose: `FIXTURES-2` is PR-B's `passport-evm-v1-swap.json`, whose
 *  `OpenSwapShielded` vectors have their own generator because its codec lives in
 *  `src/wallet/offer.ts` rather than in this file's table (question Q36). One version number
 *  per vector SET, not per file. */
export const FIXTURE_VERSION = 'AUTH-EIP712-PASSPORT-EVM-V1/FIXTURES-3';
/** Fixed seed of the deterministic generator; changing it changes the file. */
const SEED = 0x50a5590703e70001n;
/** Six random vectors per operation, so adding an operation neither starves it nor
 *  reshuffles which operation a given index lands on. */
const RANDOM_CASES_PER_OP = 6;

/** The normative test key of the EIP-712 / Ethereum literature (the key used
 *  by the reference vectors of EIP-712 itself and by AA-v3's frozen set), so a
 *  reader can check our KAT against an independent published signature. */
export const KAT_PRIVATE_KEY = fromHex(
  '0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318',
  32,
);
/** A fixed account address and domain salt; `aa…`/`dd…` as in AA-v3's set, so
 *  the two byte contracts' vectors are visibly siblings and never confusable. */
export const KAT_ACCOUNT = fromHex(`0x${'aa'.repeat(32)}`, 32);
export const KAT_SALT = fromHex(`0x${'dd'.repeat(32)}`, 32);
export const KAT_AUTH_NONCE = 7n;
export const KAT_CHALLENGE = fromHex(`0x${'11'.repeat(32)}`, 32);

class Xorshift {
  #state: bigint;
  constructor(seed: bigint) {
    this.#state = seed & ((1n << 64n) - 1n);
  }
  next64(): bigint {
    let v = this.#state;
    v ^= v >> 12n;
    v ^= (v << 25n) & ((1n << 64n) - 1n);
    v ^= v >> 27n;
    this.#state = v & ((1n << 64n) - 1n);
    return (this.#state * 0x2545f4914f6cdd1dn) & ((1n << 64n) - 1n);
  }
  bytes(length: number): Uint8Array {
    const out = new Uint8Array(length);
    let word = 0n;
    for (let i = 0; i < length; i += 1) {
      if (i % 8 === 0) word = this.next64();
      out[i] = Number((word >> BigInt((i % 8) * 8)) & 0xffn);
    }
    return out;
  }
  uint(bits: 64 | 128): bigint {
    let v = 0n;
    for (const b of this.bytes(bits / 8)) v = (v << 8n) | BigInt(b);
    return v;
  }
  privateKey(): Uint8Array {
    let scalar = 0n;
    for (const b of this.bytes(32)) scalar = (scalar << 8n) | BigInt(b);
    scalar = (scalar % (SECP256K1_N - 1n)) + 1n;
    const out = new Uint8Array(32);
    let rest = scalar;
    for (let i = 31; i >= 0 && rest > 0n; i -= 1) {
      out[i] = Number(rest & 0xffn);
      rest >>= 8n;
    }
    return out;
  }
}

const MAX_U8 = (1n << 8n) - 1n;
const MAX_U64 = (1n << 64n) - 1n;
const MAX_U128 = (1n << 128n) - 1n;

/** Where a vector's action words come from: fixed bytes for the KAT and the boundaries,
 *  the xorshift stream for the random cases. The bridge types added `address`, `u64` and
 *  `u8` to what a source must supply (project 00034 PR-G). */
interface WordSource {
  bytes32: () => Uint8Array;
  address: () => Uint8Array;
  u128: () => bigint;
  u64: () => bigint;
  u8: () => bigint;
}

function actionFields(op: EvmOp, source: WordSource): EvmMessage {
  switch (op) {
    case 'WithdrawUnshielded':
      return { color: source.bytes32(), amount: source.u128(), recipient: source.bytes32() };
    case 'WithdrawShielded':
      return {
        color: source.bytes32(),
        amount: source.u128(),
        recipientCoinPublicKey: source.bytes32(),
      };
    case 'WithdrawShieldedToContract':
      return {
        color: source.bytes32(),
        amount: source.u128(),
        recipientContract: source.bytes32(),
      };
    case 'AppendInbox':
      return { entryHash: source.bytes32() };
    case 'RotateEncKey':
      return { newKey: source.bytes32() };
    case 'AddDevice':
      return { newEntry: source.bytes32() };
    case 'RemoveDevice':
      return { entry: source.bytes32() };
    case 'BridgeDepositStart':
      return {
        erc20: source.address(),
        amount: source.u128(),
        evmNonce: source.u64(),
        gasLimit: source.u64(),
        maxFeePerGas: source.u128(),
        maxPriorityFeePerGas: source.u128(),
        keyVersion: source.u8(),
      };
    case 'BridgeWithdrawStart':
      return {
        dest: source.address(),
        color: source.bytes32(),
        amount: source.u128(),
        evmNonce: source.u64(),
        gasLimit: source.u64(),
        maxFeePerGas: source.u128(),
        maxPriorityFeePerGas: source.u128(),
        keyVersion: source.u8(),
      };
  }
}

interface VectorInput {
  label: string;
  op: EvmOp;
  privateKey: Uint8Array;
  account: Uint8Array;
  salt: Uint8Array;
  authNonce: bigint;
  challenge: Uint8Array;
  action: EvmMessage;
}

function vector(input: VectorInput) {
  const owner = addressForPrivateKey(input.privateKey);
  const message: EvmMessage = {
    account: input.account,
    owner,
    authNonce: input.authNonce,
    ...input.action,
    challenge: input.challenge,
  };
  const hashes = computeDigest(input.account, input.salt, input.op, message);
  const signature = signDigest(input.privateKey, hashes.digest);
  const wire = serializeSignature(signature);
  const recovered = recoverPoint(hashes.digest, parseSignature(wire));
  const point = publicPointForPrivateKey(input.privateKey);
  if (recovered.x !== point.x || recovered.y !== point.y) {
    throw new Error(`${input.label}: recovery does not return the signing key`);
  }
  if (!verifyDigest(hashes.digest, signature, point)) {
    throw new Error(`${input.label}: signature does not verify`);
  }
  const twin = highSTwin(signature);
  if (!verifyDigest(hashes.digest, twin, point)) {
    throw new Error(`${input.label}: the high-S twin does not verify`);
  }
  const definition = TYPE_DEFINITIONS[input.op];
  const wireMessage: Record<string, string> = {};
  for (const field of definition.fields) {
    const value = message[field.name]!;
    wireMessage[field.name] = typeof value === 'bigint' ? value.toString(10) : toHex(value);
  }
  return {
    label: input.label,
    primaryType: input.op,
    account: toHex(input.account),
    salt: toHex(input.salt),
    owner: toHex(owner),
    message: wireMessage,
    structPreimage: toHex(encodeStruct(input.op, message)),
    accountAlias: toHex(hashes.accountAlias),
    domainSeparator: toHex(hashes.domainSeparator),
    structHash: toHex(hashes.structHash),
    digest: toHex(hashes.digest),
    signature: toHex(wire),
    signatureHighSTwin: toHex(serializeSignature(twin)),
    publicPoint: {
      x: `0x${point.x.toString(16).padStart(64, '0')}`,
      y: `0x${point.y.toString(16).padStart(64, '0')}`,
      identity: false,
    },
    typedData: buildTypedData(input.account, input.salt, input.op, message),
  };
}

export function buildFixture() {
  const random = new Xorshift(SEED);
  const vectors: ReturnType<typeof vector>[] = [];

  // 1. KAT: one vector per operation, fixed inputs, the normative key.
  for (const op of EVM_OPS) {
    vectors.push(
      vector({
        label: `kat:${op}`,
        op,
        privateKey: KAT_PRIVATE_KEY,
        account: KAT_ACCOUNT,
        salt: KAT_SALT,
        authNonce: KAT_AUTH_NONCE,
        challenge: KAT_CHALLENGE,
        action: actionFields(op, {
          bytes32: () => fromHex(`0x${'cc'.repeat(32)}`, 32),
          address: () => fromHex(`0x${'cc'.repeat(20)}`, 20),
          u128: () => 4_000_000n,
          u64: () => 4_000_000n,
          u8: () => 1n,
        }),
      }),
    );
  }

  // 2. Boundaries: every word at its zero and at its maximum, both nonce ends.
  for (const op of EVM_OPS) {
    vectors.push(
      vector({
        label: `boundary:zero:${op}`,
        op,
        privateKey: KAT_PRIVATE_KEY,
        account: new Uint8Array(32),
        salt: new Uint8Array(32),
        authNonce: 0n,
        challenge: new Uint8Array(32),
        action: actionFields(op, {
          bytes32: () => new Uint8Array(32),
          address: () => new Uint8Array(20),
          u128: () => 0n,
          u64: () => 0n,
          u8: () => 0n,
        }),
      }),
    );
    vectors.push(
      vector({
        label: `boundary:max:${op}`,
        op,
        privateKey: KAT_PRIVATE_KEY,
        account: fromHex(`0x${'ff'.repeat(32)}`, 32),
        salt: fromHex(`0x${'ff'.repeat(32)}`, 32),
        authNonce: MAX_U64,
        challenge: fromHex(`0x${'ff'.repeat(32)}`, 32),
        action: actionFields(op, {
          bytes32: () => fromHex(`0x${'ff'.repeat(32)}`, 32),
          address: () => fromHex(`0x${'ff'.repeat(20)}`, 20),
          u128: () => MAX_U128,
          u64: () => MAX_U64,
          u8: () => MAX_U8,
        }),
      }),
    );
  }

  // 3. Random cases over every operation, from the fixed seed.
  const randomCases = RANDOM_CASES_PER_OP * EVM_OPS.length;
  for (let i = 0; i < randomCases; i += 1) {
    const op = EVM_OPS[i % EVM_OPS.length]!;
    vectors.push(
      vector({
        label: `random:${i}:${op}`,
        op,
        privateKey: random.privateKey(),
        account: random.bytes(32),
        salt: random.bytes(32),
        authNonce: random.uint(64),
        challenge: random.bytes(32),
        action: actionFields(op, {
          bytes32: () => random.bytes(32),
          address: () => random.bytes(20),
          u128: () => random.uint(128),
          u64: () => random.uint(64),
          u8: () => random.uint(64) & MAX_U8,
        }),
      }),
    );
  }

  return {
    version: FIXTURE_VERSION,
    note:
      'Frozen vectors of AUTH-EIP712-PASSPORT-EVM-V1. Regenerated byte-identically by '
      + 'src/tests/fixtures/generate-evm-v1.ts; any diff means the byte contract moved and '
      + 'needs a new version. All hex is lowercase and 0x-prefixed; all integers in wallet '
      + 'JSON are base-10 strings.',
    domain: {
      encodeType: DOMAIN_ENCODE_TYPE,
      name: DOMAIN_NAME,
      version: DOMAIN_VERSION,
      typeHash: toHex(DOMAIN_TYPE_HASH),
      nameHash: toHex(DOMAIN_NAME_HASH),
      versionHash: toHex(DOMAIN_VERSION_HASH),
    },
    types: Object.fromEntries(
      EVM_OPS.map((op) => [
        op,
        {
          encodeType: TYPE_DEFINITIONS[op].encodeType,
          typeHash: toHex(TYPE_HASHES[op]),
          structPreimageBytes: (TYPE_DEFINITIONS[op].fields.length + 1) * 32,
        },
      ]),
    ),
    kat: {
      privateKey: toHex(KAT_PRIVATE_KEY),
      owner: toHex(addressForPrivateKey(KAT_PRIVATE_KEY)),
      account: toHex(KAT_ACCOUNT),
      salt: toHex(KAT_SALT),
      authNonce: KAT_AUTH_NONCE.toString(10),
      challenge: toHex(KAT_CHALLENGE),
      actionWord: toHex(fromHex(`0x${'cc'.repeat(32)}`, 32)),
      amount: '4000000',
    },
    randomSeed: `0x${SEED.toString(16)}`,
    randomCases: RANDOM_CASES_PER_OP * EVM_OPS.length,
    randomCasesPerOperation: RANDOM_CASES_PER_OP,
    vectorCount: vectors.length,
    vectors,
  };
}

const here = path.dirname(fileURLToPath(import.meta.url));
export const FIXTURE_PATH = path.join(here, 'passport-evm-v1.json');

export function fixtureJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));
if (isMain) {
  const json = fixtureJson(buildFixture());
  if (process.argv.includes('--check')) {
    const existing = readFileSync(FIXTURE_PATH, 'utf8');
    if (existing !== json) {
      console.error(`FAIL: ${FIXTURE_PATH} is not what the generator produces (the byte contract moved)`);
      process.exit(1);
    }
    console.log(`OK: ${FIXTURE_PATH} regenerates byte-identically (${JSON.parse(json).vectorCount} vectors)`);
  } else {
    mkdirSync(path.dirname(FIXTURE_PATH), { recursive: true });
    writeFileSync(FIXTURE_PATH, json);
    console.log(`wrote ${FIXTURE_PATH} (${JSON.parse(json).vectorCount} vectors)`);
  }
}
