// Generator for `passport-evm-v1-swap.json` — the frozen vectors of the byte contract's EIGHTH
// type, `OpenSwapShielded`, added by project 00034 PR-B.
//
// Run: npm run fixtures:swap              (writes the file)
//      npm run fixtures:swap -- --check   (regenerates and diffs; non-zero exit if a byte moved)
//
// WHY A SECOND FILE rather than seven more vectors in `passport-evm-v1.json`.
//
// The seven types A1 froze are UNCHANGED by this work — same strings, same hashes, same vectors —
// and their fixture file is regenerated byte-identically by another line of work in the same clone
// (questions file, Q36). Appending to it would move its bytes and its version for a type its own
// generator cannot even describe (`uint8` is outside `eip712.ts`'s word table). So the eighth type
// gets its own file, versioned `…/FIXTURES-2`, and the two are folded together whenever the codecs
// are. Nothing about the byte contract is duplicated: the frame, the domain and the word rules come
// from `src/wallet/eip712.ts`, and only the new type's fields are new code.
//
// Determinism is the point, as in the A1 generator: the randomness is an xorshift64* over a fixed
// seed, never the system RNG, so a diff means the byte contract moved.

import { readFileSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  DOMAIN_ENCODE_TYPE,
  DOMAIN_NAME,
  DOMAIN_NAME_HASH,
  DOMAIN_TYPE_HASH,
  DOMAIN_VERSION,
  DOMAIN_VERSION_HASH,
  accountAlias,
  fromHex,
  toHex,
} from '../../wallet/eip712.js';
import {
  OPEN_SWAP_ENCODE_TYPE,
  OPEN_SWAP_FIELDS,
  OPEN_SWAP_PRIMARY_TYPE,
  OPEN_SWAP_TYPE_HASH,
  RECIPIENT_NAMED_COIN_KEY,
  RECIPIENT_OPEN,
  buildOpenSwapTypedData,
  encodeOpenSwapStruct,
  openSwapDigest,
  type OpenSwapMessage,
} from '../../wallet/offer.js';
import {
  SECP256K1_N,
  addressForPrivateKey,
  highSTwin,
  parseSignature,
  publicPointForPrivateKey,
  recoverPoint,
  serializeSignature,
  signDigest,
  verifyDigest,
} from '../../wallet/evm-signature.js';

export const FIXTURE_VERSION = 'AUTH-EIP712-PASSPORT-EVM-V1/FIXTURES-2';
/** Fixed seed of the deterministic generator; changing it changes the file. */
const SEED = 0x50a5590703e70002n;
const RANDOM_CASES = 12;

/** The same normative key, account, salt, nonce and challenge the A1 set uses, so the eighth type's
 *  KAT is directly comparable with the other seven. */
export const KAT_PRIVATE_KEY = fromHex(
  '0x4c0883a69102937d6231471b5dbb6204fe5129617082792ae468d01a3f362318',
  32,
);
export const KAT_ACCOUNT = fromHex(`0x${'aa'.repeat(32)}`, 32);
export const KAT_SALT = fromHex(`0x${'dd'.repeat(32)}`, 32);
export const KAT_AUTH_NONCE = 7n;
export const KAT_CHALLENGE = fromHex(`0x${'11'.repeat(32)}`, 32);

class Xorshift {
  #state: bigint;
  constructor(seed: bigint) {
    this.#state = seed & ((1n << 64n) - 1n);
  }
  next64(): bigint {
    let v = this.#state;
    v ^= v >> 12n;
    v ^= (v << 25n) & ((1n << 64n) - 1n);
    v ^= v >> 27n;
    this.#state = v & ((1n << 64n) - 1n);
    return (this.#state * 0x2545f4914f6cdd1dn) & ((1n << 64n) - 1n);
  }
  bytes(length: number): Uint8Array {
    const out = new Uint8Array(length);
    let word = 0n;
    for (let i = 0; i < length; i += 1) {
      if (i % 8 === 0) word = this.next64();
      out[i] = Number((word >> BigInt((i % 8) * 8)) & 0xffn);
    }
    return out;
  }
  uint(bits: 64 | 128): bigint {
    let v = 0n;
    for (const b of this.bytes(bits / 8)) v = (v << 8n) | BigInt(b);
    return v;
  }
  privateKey(): Uint8Array {
    let scalar = 0n;
    for (const b of this.bytes(32)) scalar = (scalar << 8n) | BigInt(b);
    scalar = (scalar % (SECP256K1_N - 1n)) + 1n;
    const out = new Uint8Array(32);
    let rest = scalar;
    for (let i = 31; i >= 0 && rest > 0n; i -= 1) {
      out[i] = Number(rest & 0xffn);
      rest >>= 8n;
    }
    return out;
  }
}

const MAX_U64 = (1n << 64n) - 1n;
const MAX_U128 = (1n << 128n) - 1n;

interface VectorInput {
  label: string;
  privateKey: Uint8Array;
  salt: Uint8Array;
  message: Omit<OpenSwapMessage, 'owner'>;
}

function vector(input: VectorInput) {
  const owner = addressForPrivateKey(input.privateKey);
  const message: OpenSwapMessage = { ...input.message, owner };
  const hashes = openSwapDigest(input.salt, message);
  const signature = signDigest(input.privateKey, hashes.digest);
  const wire = serializeSignature(signature);
  const recovered = recoverPoint(hashes.digest, parseSignature(wire));
  const point = publicPointForPrivateKey(input.privateKey);
  if (recovered.x !== point.x || recovered.y !== point.y) {
    throw new Error(`${input.label}: recovery does not return the signing key`);
  }
  if (!verifyDigest(hashes.digest, signature, point)) {
    throw new Error(`${input.label}: signature does not verify`);
  }
  const twin = highSTwin(signature);
  if (!verifyDigest(hashes.digest, twin, point)) {
    throw new Error(`${input.label}: the high-S twin does not verify`);
  }
  const wireMessage: Record<string, string> = {};
  for (const field of OPEN_SWAP_FIELDS) {
    const value = (message as unknown as Record<string, Uint8Array | bigint>)[field.name]!;
    wireMessage[field.name] = typeof value === 'bigint' ? value.toString(10) : toHex(value);
  }
  return {
    label: input.label,
    primaryType: OPEN_SWAP_PRIMARY_TYPE,
    account: toHex(message.account),
    salt: toHex(input.salt),
    owner: toHex(owner),
    message: wireMessage,
    structPreimage: toHex(encodeOpenSwapStruct(message)),
    accountAlias: toHex(accountAlias(message.account)),
    domainSeparator: toHex(hashes.domainSeparator),
    structHash: toHex(hashes.structHash),
    digest: toHex(hashes.digest),
    signature: toHex(wire),
    signatureHighSTwin: toHex(serializeSignature(twin)),
    publicPoint: {
      x: `0x${point.x.toString(16).padStart(64, '0')}`,
      y: `0x${point.y.toString(16).padStart(64, '0')}`,
      identity: false,
    },
    typedData: buildOpenSwapTypedData(input.salt, message),
  };
}

export function buildFixture() {
  const random = new Xorshift(SEED);
  const vectors: ReturnType<typeof vector>[] = [];
  const word = (b: number) => fromHex(`0x${b.toString(16).padStart(2, '0').repeat(32)}`, 32);

  // 1. KAT, one per recipient kind — the two shapes are the point of this type.
  vectors.push(
    vector({
      label: 'kat:open',
      privateKey: KAT_PRIVATE_KEY,
      salt: KAT_SALT,
      message: {
        account: KAT_ACCOUNT,
        authNonce: KAT_AUTH_NONCE,
        giveColor: word(0xcc),
        giveAmount: 4_000_000n,
        recipientKind: RECIPIENT_OPEN,
        recipient: new Uint8Array(32),
        wantNonce: word(0xbb),
        wantColor: word(0x99),
        wantAmount: 7_000_000n,
        validUntil: 0n,
        challenge: KAT_CHALLENGE,
      },
    }),
  );
  vectors.push(
    vector({
      label: 'kat:named',
      privateKey: KAT_PRIVATE_KEY,
      salt: KAT_SALT,
      message: {
        account: KAT_ACCOUNT,
        authNonce: KAT_AUTH_NONCE,
        giveColor: word(0xcc),
        giveAmount: 4_000_000n,
        recipientKind: RECIPIENT_NAMED_COIN_KEY,
        recipient: word(0x77),
        wantNonce: word(0xbb),
        wantColor: word(0x99),
        wantAmount: 7_000_000n,
        validUntil: 1_800_003_600n,
        challenge: KAT_CHALLENGE,
      },
    }),
  );

  // 2. Boundaries: every word at its zero, then every word at its maximum.
  vectors.push(
    vector({
      label: 'boundary:zero',
      privateKey: KAT_PRIVATE_KEY,
      salt: new Uint8Array(32),
      message: {
        account: new Uint8Array(32),
        authNonce: 0n,
        giveColor: new Uint8Array(32),
        giveAmount: 0n,
        recipientKind: 0n,
        recipient: new Uint8Array(32),
        wantNonce: new Uint8Array(32),
        wantColor: new Uint8Array(32),
        wantAmount: 0n,
        validUntil: 0n,
        challenge: new Uint8Array(32),
      },
    }),
  );
  vectors.push(
    vector({
      label: 'boundary:max',
      privateKey: KAT_PRIVATE_KEY,
      salt: word(0xff),
      message: {
        account: word(0xff),
        authNonce: MAX_U64,
        giveColor: word(0xff),
        giveAmount: MAX_U128,
        // The largest value the FIELD admits, not the largest the circuit accepts: the byte contract
        // is about encoding, and `assert_open_swap_terms` is what refuses kinds above 1.
        recipientKind: 255n,
        recipient: word(0xff),
        wantNonce: word(0xff),
        wantColor: word(0xff),
        wantAmount: MAX_U128,
        validUntil: MAX_U64,
        challenge: word(0xff),
      },
    }),
  );

  // 3. Random cases from the fixed seed, alternating the recipient kind.
  for (let i = 0; i < RANDOM_CASES; i += 1) {
    const kind = BigInt(i % 2);
    vectors.push(
      vector({
        label: `random:${i}:${kind === RECIPIENT_OPEN ? 'open' : 'named'}`,
        privateKey: random.privateKey(),
        salt: random.bytes(32),
        message: {
          account: random.bytes(32),
          authNonce: random.uint(64),
          giveColor: random.bytes(32),
          giveAmount: random.uint(128),
          recipientKind: kind,
          recipient: kind === RECIPIENT_OPEN ? new Uint8Array(32) : random.bytes(32),
          wantNonce: random.bytes(32),
          wantColor: random.bytes(32),
          wantAmount: random.uint(128),
          validUntil: random.uint(64),
          challenge: random.bytes(32),
        },
      }),
    );
  }

  return {
    version: FIXTURE_VERSION,
    note:
      'Frozen vectors of the EIGHTH primary type of AUTH-EIP712-PASSPORT-EVM-V1, OpenSwapShielded '
      + '(project 00034 PR-B). The other seven types are unchanged and live in passport-evm-v1.json '
      + '(FIXTURES-1). Regenerated byte-identically by src/tests/fixtures/generate-evm-v1-swap.ts; '
      + 'any diff means the byte contract moved and needs a new version. All hex is lowercase and '
      + '0x-prefixed; all integers in wallet JSON are base-10 strings.',
    domain: {
      encodeType: DOMAIN_ENCODE_TYPE,
      name: DOMAIN_NAME,
      version: DOMAIN_VERSION,
      typeHash: toHex(DOMAIN_TYPE_HASH),
      nameHash: toHex(DOMAIN_NAME_HASH),
      versionHash: toHex(DOMAIN_VERSION_HASH),
    },
    types: {
      [OPEN_SWAP_PRIMARY_TYPE]: {
        encodeType: OPEN_SWAP_ENCODE_TYPE,
        typeHash: toHex(OPEN_SWAP_TYPE_HASH),
        structPreimageBytes: (OPEN_SWAP_FIELDS.length + 1) * 32,
      },
    },
    kat: {
      privateKey: toHex(KAT_PRIVATE_KEY),
      owner: toHex(addressForPrivateKey(KAT_PRIVATE_KEY)),
      account: toHex(KAT_ACCOUNT),
      salt: toHex(KAT_SALT),
      authNonce: KAT_AUTH_NONCE.toString(10),
      challenge: toHex(KAT_CHALLENGE),
    },
    randomSeed: `0x${SEED.toString(16)}`,
    randomCases: RANDOM_CASES,
    vectorCount: vectors.length,
    vectors,
  };
}

const here = path.dirname(fileURLToPath(import.meta.url));
export const FIXTURE_PATH = path.join(here, 'passport-evm-v1-swap.json');

export function fixtureJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));
if (isMain) {
  const json = fixtureJson(buildFixture());
  if (process.argv.includes('--check')) {
    const existing = readFileSync(FIXTURE_PATH, 'utf8');
    if (existing !== json) {
      console.error(`${FIXTURE_PATH} is not byte-identical to a fresh generation — the byte contract moved`);
      process.exit(1);
    }
    console.log(`${FIXTURE_PATH}: OK (byte-identical)`);
  } else {
    writeFileSync(FIXTURE_PATH, json);
    console.log(`wrote ${FIXTURE_PATH}`);
  }
}
