#!/usr/bin/env bash
# run-f4.sh — compile, bring the F4 localnet up, run the end-to-end driver, tear down.
#
# Project 00034, sub-plan plans/00034-sub-f-vault-fork.md, phase F4.
#
# Usage:
#   ./run-f4.sh compile     # contracts + the claimer (offline, no Docker)
#   ./run-f4.sh up          # node, indexer, proof server, anvil (NOT fakenet — see below)
#   ./run-f4.sh e2e         # the driver; it starts fakenet itself once the singleton exists
#   ./run-f4.sh down        # docker compose down -v
#   ./run-f4.sh logs        # fakenet responder logs
#   ./run-f4.sh all         # compile + up + e2e + down
#
# HOST RULE: only ONE localnet stack runs on this host at a time. Before `up`, read the
# "Stack in use" line at the top of
# plans/00034-passport-evm-account-zswap-questions.md; claim it there, and clear it after
# `down`. This script does not touch that file — claiming is an agent decision, not a side
# effect of running a command.
#
# fakenet is deliberately NOT started by `up`: it needs MPC_ROOT_KEY and the singleton's
# address, and both exist only after the driver has generated the key and deployed the
# contract. The driver starts it itself at step S2.
#
# Every published port is >= 10000 and overridable; the compose project name is unique.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/infra"

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-prf-erc20-vault}"
export NODE_PORT="${NODE_PORT:-19844}"
export NODE_P2P_PORT="${NODE_P2P_PORT:-19833}"
export INDEXER_PORT="${INDEXER_PORT:-18188}"
export PROOF_PORT="${PROOF_PORT:-16400}"
export EVM_PORT="${EVM_PORT:-18545}"

export NODE_URL="http://localhost:$NODE_PORT"
export INDEXER_URL="http://localhost:$INDEXER_PORT/api/v4/graphql"
export INDEXER_WS_URL="ws://localhost:$INDEXER_PORT/api/v4/graphql/ws"
export PROOF_SERVER_URL="http://127.0.0.1:$PROOF_PORT"
export EVM_RPC_URL="http://127.0.0.1:$EVM_PORT"
export MIDNIGHT_NETWORK=local

compose() { docker compose -f "$INFRA_DIR/docker-compose.yml" --env-file "$INFRA_DIR/.env" "$@"; }

ensure_env() {
  if [[ ! -f "$INFRA_DIR/.env" ]]; then
    cat > "$INFRA_DIR/.env" <<EOF
# Generated by run-f4.sh — never committed (see .gitignore).
APP__INFRA__SECRET=$(openssl rand -hex 32)

# Fixed demo seed (do not use in production). The dev node genesis funds it.
WALLET_SEED=0000000000000000000000000000000000000000000000000000000000000001
EOF
    echo "infra/.env created"
  fi
  set -a; source "$INFRA_DIR/.env"; set +a
}

do_compile() {
  cd "$SCRIPT_DIR"
  echo "Compiling with real proving keys (callee before caller — the artefact directory name IS the ABI)"
  npm run compile
  COMPACT_PATH=node_modules compact compile +0.34.0 --feature-zkir-v3 \
    --compact-path node_modules:managed e2e/vault-claimer.compact managed/VaultClaimer
}

do_up() {
  ensure_env
  cd "$SCRIPT_DIR"
  echo "=== F4 localnet: project $COMPOSE_PROJECT_NAME, ports $NODE_PORT/$INDEXER_PORT/$PROOF_PORT/$EVM_PORT ==="
  compose up -d node indexer proof-server evm

  echo -n "Waiting for node"
  ELAPSED=0
  until curl -sf "http://localhost:$NODE_PORT/health" > /dev/null 2>&1; do
    if (( ELAPSED >= 90 )); then echo " FAILED"; compose logs node --tail 30; exit 1; fi
    printf "."; sleep 2; (( ELAPSED += 2 ))
  done
  echo " OK"

  echo -n "Waiting for indexer"
  # Cold-start quirk: an indexer started before the node produces block 1 can exit once;
  # re-up it periodically while waiting to absorb that.
  ELAPSED=0
  until curl -sf "http://localhost:$INDEXER_PORT/api/v4/graphql" -H 'Content-Type: application/json' \
      -d '{"query":"{ __typename }"}' > /dev/null 2>&1; do
    if (( ELAPSED >= 180 )); then echo " NOT READY"; compose logs indexer --tail 30; break; fi
    if (( ELAPSED > 0 && ELAPSED % 21 == 0 )); then compose up -d indexer > /dev/null 2>&1 || true; fi
    printf "."; sleep 3; (( ELAPSED += 3 ))
  done
  echo " OK"

  echo -n "Waiting for proof server"
  ELAPSED=0
  until curl -sf "http://localhost:$PROOF_PORT/version" > /dev/null 2>&1; do
    if (( ELAPSED >= 60 )); then echo " NOT RESPONDING"; break; fi
    printf "."; sleep 2; (( ELAPSED += 2 ))
  done
  echo " OK"

  echo -n "Waiting for anvil"
  ELAPSED=0
  until curl -sf "$EVM_RPC_URL" -H 'Content-Type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' > /dev/null 2>&1; do
    if (( ELAPSED >= 60 )); then echo " NOT RESPONDING"; compose logs evm --tail 20; break; fi
    printf "."; sleep 2; (( ELAPSED += 2 ))
  done
  echo " OK"
}

do_e2e() {
  ensure_env
  cd "$SCRIPT_DIR"
  npx tsx e2e/run-e2e.ts
}

do_logs() {
  ensure_env
  cd "$SCRIPT_DIR"
  compose logs fakenet --tail "${1:-80}"
}

do_down() {
  ensure_env
  cd "$SCRIPT_DIR"
  compose --profile fakenet down -v || true
  rm -rf midnight-level-db
  echo "stack down, volumes removed"
}

CMD="${1:-all}"; shift || true
case "$CMD" in
  compile) do_compile ;;
  up)      do_up ;;
  e2e)     do_e2e ;;
  logs)    do_logs "$@" ;;
  down)    do_down ;;
  all)     do_compile; do_up; do_e2e; do_down ;;
  *)       echo "usage: $0 {compile|up|e2e|logs|down|all}"; exit 2 ;;
esac
