#!/usr/bin/env bash
# run-sl.sh — the LOCAL dress rehearsal of PR-S: the complete Test 3 story on a localnet.
#
# Project 00034, sub-plan plans/00034-sub-s-stagenet-bridge.md, phase S-L.
#
# It runs the SAME driver PR-S runs on stagenet (src/tests/stagenet-run.ts) under its
# `local` network profile, against the five-container stack PR-F and PR-G proved the bridge
# on: node 2.1.0 / indexer 4.4.0-rc.2 / proof-server 9.0.0-rc.6 / anvil with a locally
# deployed ERC20 / the Sig Network fakenet MPC responder. It exists because stagenet's MPC
# stopped signing (question Q61) and the owner's question is about the design.
#
# Usage:
#   ./run-sl.sh compile   # the vault, the singleton and the account (offline, no Docker)
#   ./run-sl.sh up        # node, indexer, proof server, anvil (NOT fakenet — see below)
#   ./run-sl.sh story     # l0 → s8, the whole Test 3 story, against a stack that is up
#   ./run-sl.sh <cmd>     # one driver command (l0, s1, s2, s3-fund, …, s8, status)
#   ./run-sl.sh logs      # fakenet responder logs
#   ./run-sl.sh down      # docker compose down -v
#   ./run-sl.sh all       # compile + up + story + down
#
# HOST RULE: only ONE localnet stack runs on this host at a time. Before `up`, read the
# "Stack in use" line at the top of
# plans/00034-passport-evm-account-zswap-questions.md; claim it there (APPEND to the line,
# do not replace another agent's claim), and clear it after `down`. This script does not
# touch that file — claiming is an agent decision, not a side effect of running a command.
#
# fakenet is deliberately NOT started by `up`: it needs MPC_ROOT_KEY and the singleton's
# address, and both exist only after the driver has generated the key and deployed the
# contract. The driver starts it itself, in `l0`.
#
# The compose file is PR-F's; only the project name and the ports differ, so an S-L run can
# never collide with an F4 or G4 one.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # contracts/erc20-vault
ACCOUNT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"               # contract/
INFRA_DIR="$SCRIPT_DIR/infra"

export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-prsl-local}"
export NODE_PORT="${NODE_PORT:-24944}"
export NODE_P2P_PORT="${NODE_P2P_PORT:-24933}"
export INDEXER_PORT="${INDEXER_PORT:-24188}"
export PROOF_PORT="${PROOF_PORT:-24400}"
export EVM_PORT="${EVM_PORT:-24545}"

export NODE_URL="http://localhost:$NODE_PORT"
export MIDNIGHT_NODE_URL="$NODE_URL"
export INDEXER_URL="http://localhost:$INDEXER_PORT/api/v4/graphql"
export INDEXER_WS_URL="ws://localhost:$INDEXER_PORT/api/v4/graphql/ws"
export PROOF_SERVER_URL="http://127.0.0.1:$PROOF_PORT"
export MIDNIGHT_PROOF_SERVER_URL="$PROOF_SERVER_URL"
export EVM_RPC_URL="http://127.0.0.1:$EVM_PORT"
export MIDNIGHT_NETWORK=local
export MIDNIGHT_NETWORK_ID=undeployed
export PRS_PROFILE=local

# The two LOCAL genesis wallets: `…0001` deploys and pays (wallet 1), `…0002` is Test 3's
# second wallet. Both are funded by the dev preset's genesis and generate their own DUST.
export WALLET_SEED="${WALLET_SEED:-0000000000000000000000000000000000000000000000000000000000000001}"
export WALLET_SEED_SECONDARY="${WALLET_SEED_SECONDARY:-0000000000000000000000000000000000000000000000000000000000000002}"

# The fakenet responder pays its own Midnight fees from a genesis seed too. It is wallet 1's
# seed, which is the compose file's default and exactly what PR-G's green localnet bridge
# e2e ran on — a third seed would be tidier but its genesis funding is not established, and
# an unfunded responder is a silent, hour-long failure.
export MPC_RESPONDER_SEED="${MPC_RESPONDER_SEED:-0000000000000000000000000000000000000000000000000000000000000001}"

export PRS_EVIDENCE_DIR="${PRS_EVIDENCE_DIR:-/Users/edwardalvarado/todo/AA/evidence/00034-passport-evm-account-zswap/pr-s-local}"
# Outside the repository and outside ~/.config/aa-00034 (which holds the owner's real seeds
# and is not read by this profile at all): everything in it is a throwaway localnet secret.
export PRS_STATE="${PRS_STATE:-$HOME/.cache/aa-00034/local-prs-state.json}"

compose() { docker compose -f "$INFRA_DIR/docker-compose.yml" --env-file "$INFRA_DIR/.env" "$@"; }

ensure_env() {
  if [[ ! -f "$INFRA_DIR/.env" ]]; then
    cat > "$INFRA_DIR/.env" <<EOF
# Generated by run-sl.sh — never committed (see .gitignore).
APP__INFRA__SECRET=$(openssl rand -hex 32)

# Fixed demo seed (do not use in production). The dev node genesis funds it.
WALLET_SEED=0000000000000000000000000000000000000000000000000000000000000001
EOF
    echo "infra/.env created"
  fi
  set -a; source "$INFRA_DIR/.env"; set +a
  # infra/.env pins WALLET_SEED for the compose file's own use; the exports above are what
  # the driver reads, so re-assert them after sourcing.
  export WALLET_SEED="${WALLET_SEED:-0000000000000000000000000000000000000000000000000000000000000001}"
  export WALLET_SEED_SECONDARY="0000000000000000000000000000000000000000000000000000000000000002"
}

do_compile() {
  cd "$SCRIPT_DIR"
  echo "=== the vault and the singleton (callees first — the artefact directory name IS the ABI)"
  npm run compile
  cd "$ACCOUNT_DIR"
  echo "=== the account (links contracts/managed/{Erc20Vault,SignetSigner}, then compiles)"
  npm run compile:account
}

wait_for() {
  local label="$1" url="$2" limit="$3"; shift 3
  printf "Waiting for %s" "$label"
  local elapsed=0
  until curl -sf "$url" "$@" > /dev/null 2>&1; do
    if (( elapsed >= limit )); then echo " NOT READY"; return 1; fi
    printf "."; sleep 2; (( elapsed += 2 ))
  done
  echo " OK"
}

do_up() {
  ensure_env
  cd "$SCRIPT_DIR"
  echo "=== S-L localnet: project $COMPOSE_PROJECT_NAME, ports $NODE_PORT/$INDEXER_PORT/$PROOF_PORT/$EVM_PORT ==="
  compose up -d node indexer proof-server evm
  wait_for "node" "http://localhost:$NODE_PORT/health" 90 || { compose logs node --tail 30; exit 1; }
  # Cold-start quirk: an indexer started before the node produces block 1 can exit once.
  printf "Waiting for indexer"
  local elapsed=0
  until curl -sf "http://localhost:$INDEXER_PORT/api/v4/graphql" -H 'Content-Type: application/json' \
      -d '{"query":"{ __typename }"}' > /dev/null 2>&1; do
    if (( elapsed >= 180 )); then echo " NOT READY"; compose logs indexer --tail 30; break; fi
    if (( elapsed > 0 && elapsed % 21 == 0 )); then compose up -d indexer > /dev/null 2>&1 || true; fi
    printf "."; sleep 3; (( elapsed += 3 ))
  done
  echo " OK"
  wait_for "proof server" "http://localhost:$PROOF_PORT/version" 60 || true
  wait_for "anvil" "$EVM_RPC_URL" 60 -H 'Content-Type: application/json' \
    -d '{"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}' || { compose logs evm --tail 20; exit 1; }
}

driver() { ensure_env; cd "$ACCOUNT_DIR"; npx tsx src/tests/stagenet-run.ts "$@"; }

do_story() {
  for cmd in l0 s1 s2 s3-fund s3-start s3-relay s3-complete s4 s5 s6 s7-gas s7-start s7-relay s7-complete s8; do
    echo
    echo "────────────────────────────────────────────────────────── $cmd"
    driver "$cmd"
  done
}

do_logs() { ensure_env; cd "$SCRIPT_DIR"; compose logs fakenet --tail "${1:-80}"; }

do_down() {
  ensure_env
  cd "$SCRIPT_DIR"
  compose --profile fakenet down -v || true
  rm -rf "$ACCOUNT_DIR/midnight-level-db" "$SCRIPT_DIR/midnight-level-db"
  echo "stack down, volumes removed"
}

CMD="${1:-all}"; shift || true
case "$CMD" in
  compile) do_compile ;;
  up)      do_up ;;
  story)   do_story ;;
  logs)    do_logs "$@" ;;
  down)    do_down ;;
  all)     do_compile; do_up; do_story; do_down ;;
  *)       driver "$CMD" "$@" ;;
esac
